app/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from app import settings
from home import views

urlpatterns = patterns('',
    url(r'^$', views.login, name='login'),
    url(r'^home$', views.home, name='home'),
    url(r'^profile', views.profile, name='profile'),
    # url(r'^battle', views.battle, name='battle'),
    url(r'^battle/', include('battle.urls', namespace='battle')),

    url(r'^tweet', views.tweet, name='tweet'),
    url(r'^query', views.query, name='query'),
    url(r'^media/photo', views.media_photo, name='media_photo'),
    url(r'^media/video', views.media_video, name='media_video'),
    url(r'^media/inspector', views.media_inspector, name='media_inspector'),
    url(r'^media', views.media_video, name='media_video'),
    url(r'^logout$', views.logout, name='logout'),
    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^admin/', admin.site.urls),
)

urlpatterns += patterns('', (r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}), )

battle/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
  url(r'^$', views.BattleList.as_view(), name='battle_list'),
  url(r'^new$', views.BattleCreate.as_view(), name='battle_new'),
  url(r'^detail/(?P<pk>\d+)$', views.BattleDetailView.as_view(), name='battle_detail'),
  url(r'^edit/(?P<pk>\d+)$', views.BattleUpdate.as_view(), name='battle_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.BattleDelete.as_view(), name='battle_delete'),
)

battle/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible  # needed to support Python 2
class Battle(models.Model):
    battle_name = models.CharField(max_length=100)
    hashtag1 = models.CharField(max_length=500)
    hashtag1_typos = models.CharField(null=True, max_length=100, blank=True)
    hashtag2 = models.CharField(max_length=500)
    hashtag2_typos = models.CharField(null=True, max_length=100, blank=True)
    started_at = models.CharField(max_length=100)
    ended_at = models.CharField(max_length=100)
    winner = models.CharField(null=True, max_length=500, blank=True)
    status = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="+")

    def __unicode__(self):
        return self.battle_name

    def __str__(self):
        return str(self.battle_name)

    def get_absolute_url(self):
        return reverse('battle:battle_edit', kwargs={'pk': self.pk})

battle/views.py
import datetime

from django.http import JsonResponse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy

from home.views import get_twitter
from .models import Battle
from . import spellCheck


class AjaxableResponseMixin(object):
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """
    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        form.instance.user = self.request.user
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
            }
            return JsonResponse(data)
        else:
            return response


class BattleList(ListView):
    model = Battle


class BattleCreate(CreateView):
    model = Battle
    fields = ['battle_name', 'hashtag1', 'hashtag2', 'started_at', 'ended_at']
    success_url = reverse_lazy('battle:battle_list')

    def form_valid(self, form):

        context = battle(self.request)

        form.instance.hashtag1_typos = context["query1_typos"]
        form.instance.hashtag2_typos = context["query2_typos"]
        form.instance.winner = context["winner"]
        form.instance.status = context["status"]
        form.instance.user = self.request.user

        return super(BattleCreate, self).form_valid(form)


class BattleDetailView(DetailView):
    model = Battle
    template_name = "battle/battle_detail.html"


class BattleUpdate(UpdateView):
    model = Battle
    fields = ['battle_name', 'hashtag1', 'hashtag2', 'started_at', 'ended_at']
    success_url = reverse_lazy('battle:battle_list')

    def form_valid(self, form):

        context = battle(self.request)

        form.instance.hashtag1_typos = context["query1_typos"]
        form.instance.hashtag2_typos = context["query2_typos"]
        form.instance.winner = context["winner"]
        form.instance.status = context["status"]
        form.instance.user = self.request.user

        return super(BattleUpdate, self).form_valid(form)


class BattleDelete(AjaxableResponseMixin, DeleteView):
    model = Battle
    success_url = reverse_lazy('battle:battle_list')


@login_required
def battle(request):

    hashtag1 = request.POST.get("hashtag1", None)
    hashtag2 = request.POST.get("hashtag2", None)
    started_at = request.POST.get("started_at", None)
    ended_at = request.POST.get("ended_at", None)

    api = get_twitter(request.user)

    statuses1 = []
    statuses2 = []

    status1_ended_at = datetime.datetime.strptime(ended_at, "%Y-%m-%d").date() + datetime.timedelta(days=1)
    status1_ended_at = status1_ended_at.strftime("%Y-%m-%d")

    status2_ended_at = datetime.datetime.strptime(ended_at, "%Y-%m-%d").date() + datetime.timedelta(days=1)
    status2_ended_at = status2_ended_at.strftime("%Y-%m-%d")

    today = datetime.datetime.today()
    today = today.strftime("%Y-%m-%d")

    query1_typos = None
    query2_typos = None
    winner = None
    status = "Inactive"

    # get a query of tweets by hashtags and start date/end date
    while hashtag1 and len(hashtag1) > 1 and hashtag2 and len(hashtag2) > 1 and started_at and ended_at  and started_at < today:
        new_statuses1 = api.GetSearch(term=hashtag1, count=100, until=status1_ended_at, result_type='recent')
        new_statuses2 = api.GetSearch(term=hashtag2, count=100, until=status2_ended_at, result_type='recent')

        # out of statuses: done
        if len(new_statuses1) == 0 or len(new_statuses2) == 0:
            break

        statuses1 = statuses1 + new_statuses1
        statuses2 = statuses2 + new_statuses2

        # get the created_at of the oldest tweet in a response query1
        status1_date_string = new_statuses1[len(new_statuses1) - 1].created_at
        dt1 = status1_date_string.split(" ")
        status1_ended_at = datetime.datetime.strptime(dt1[5] + "-" + dt1[1] + "-" + dt1[2], "%Y-%b-%d").date()
        status1_ended_at = status1_ended_at.strftime("%Y-%m-%d")

        # get the created_at of the oldest tweet in a response query2
        status2_date_string = new_statuses2[len(new_statuses2) - 1].created_at
        dt2 = status2_date_string.split(" ")
        status2_ended_at = datetime.datetime.strptime(dt2[5] + "-" + dt2[1] + "-" + dt2[2], "%Y-%b-%d").date()
        status2_ended_at = status2_ended_at.strftime("%Y-%m-%d")

        # reached started_at: done
        if started_at >= status1_ended_at or started_at >= status2_ended_at:
            break

    # calculate the number of typos if a query of tweets is not empty
    if len(statuses1) > 0 and len(statuses2) > 0:
        query1_typos = spellCheck.preprocess(statuses1)
        query2_typos = spellCheck.preprocess(statuses2)

    # compare the number of typos between two queries of tweets
    if query1_typos or query2_typos:
        if query2_typos < query1_typos:
            winner = hashtag2
        else:
            winner = hashtag1

    # estimate the status of battle
    if len(statuses1) != 0 and len(statuses2) != 0:
        status = "Active"

    context = {
        'request': request,
        'statuses1': statuses1,
        'query1_typos': query1_typos,
        'statuses2': statuses2,
        'query2_typos': query2_typos,
        'winner': winner,
        'status': status
    }

    return context

templates/battle/battle_detail.html
{% extends "base.html" %}

{% load static %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Battle Detail View{% endblock %}

{% block content %}

    <div class="row text-center">
        <h3>[ <strong style="color: #0000FF;">BID.{{ battle.id }}</strong> ] Battle Detail View</h3>
    </div>

    <br>

    <table class="table table-striped table-bordered" align="center" style="width: 70%;">
        <colgroup>
            <col width="20%"/>
            <col width="40%"/>
            <col width="40%"/>
        </colgroup>
        <thead>
            <tr>
                <th colspan="3" class="text-center" style="background-color: #DFF0D8;">
                    <h4> Winning Hashtag : <strong style="color: #d9534f;">{{ battle.winner }}</strong></h4>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="background-color: #FAEBCC;"> <strong>Description</strong></td>
                <td colspan="2">
                    This battle named "<strong style="color: #C37E05;">{{ battle.battle_name }}</strong>" was progressed from <strong style="color: #5BC0DE;">{{ battle.started_at }}</strong> to <strong style="color: #5BC0DE;">{{ battle.ended_at }}</strong>.
                </td>
            </tr>
            <tr>
                <td style="background-color: #FAEBCC;"> <strong>Hashtags</strong></td>
                <td> {{ battle.hashtag1 }} </td>
                <td> {{ battle.hashtag2 }} </td>
            </tr>
            <tr>
                <td style="background-color: #FAEBCC;"> <strong>Number of Typos</strong></td>
                <td> {{ battle.hashtag1_typos }} </td>
                <td> {{ battle.hashtag2_typos }} </td>
            </tr>
        </tbody>
    </table>

    <div class="row text-center">
        <a class="btn btn-default" href="{% url 'battle:battle_list' %}"><i class="fa fa-arrow-left"></i> Back to List </a>
        <a class="btn btn-default" href="{% url 'battle:battle_edit' battle.id %}" style="margin-left: 5px;"><i class="fa fa-arrow-right"></i> Go to Settings</a>
    </div>

{% endblock %}

{% block extra_script %}
{% endblock %}

templates/battle/battle_form.html
{% extends "base.html" %}

{% load static %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Battle of Hashtags{% endblock %}

{% block content %}

    <form class="form-horizontal" method="post">
        {% csrf_token %}

        <h3 class="text-center"> Battle between two hashtags </h3>
        <br>

        <div class="row">
            <div class="col-sm-offset-1 col-sm-5">
                <div class="form-group">
                    <label for="battle_name" class="col-sm-3 control-label text-right">Battle Name</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="battle_name" name="battle_name" placeholder="Type your battle name" {% if battle %} value="{{ battle.battle_name }}" {% endif %}>
                    </div>
                </div>

                <div class="form-group">
                    <label for="hashtag1" class="col-sm-3 control-label text-right">Hashtag1</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="hashtag1" name="hashtag1" placeholder="Type a hashtag: for example, #hashtag" {% if battle %} value="{{ battle.hashtag1 }}" {% endif %}>
                    </div>
                </div>

                <div class="form-group">
                    <label for="hashtag2" class="col-sm-3 control-label text-right">Hashtag2</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="hashtag2" name="hashtag2" placeholder="Type a hashtag: for example, #hashtag" {% if battle %} value="{{ battle.hashtag2 }}" {% endif %}>
                    </div>
                </div>
            </div>

            <div class="col-sm-6">
                <div class="form-group">
                    <label for="started_at" class="col-sm-2 control-label text-right">Start Date</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="started_at" name="started_at" {% if battle %} value="{{ battle.started_at }}" {% endif %}>
                    </div>
                </div>

                <div class="form-group">
                    <label for="ended_at" class="col-sm-2 control-label text-right">End Date</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="ended_at" name="ended_at" {% if battle %} value="{{ battle.ended_at }}" {% endif %}>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-offset-2 col-sm-5">
                <div class="form-group">
                    <div class="col-sm-offset-1">
                        <button type="submit" class="btn btn-primary">{% if battle %} Update {% else %} Create {% endif %} Battle</button>
                        <a class="btn btn-default" href="{% url 'battle:battle_list' %}" style="margin-left: 5px;"><i class="fa fa-times"></i> Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

{% block extra_script %}
    <script>

        ///////////////////////////////////////////////////////
        // Start & End date configuration
        ///////////////////////////////////////////////////////

        var dateToDisable = new Date();
	    dateToDisable.setDate(dateToDisable.getDate() - 7);

        $('#started_at').datetimepicker({
            format: 'Y-m-d',
            timepicker: false,
            minDate: dateToDisable,
            onSelectDate: function(selected) { // if started_at is selected

                var dt = new Date(selected);
                dt.setDate(selected.getDate() + 1);
                $('#ended_at').datetimepicker({
                    minDate: dt
                });
            }
        });

        $('#started_at').focus( function() {  // if ended_at is empty

            var dt = $('#ended_at').val();
            if (!dt) {
                $(this).datetimepicker({ maxDate: false });
            }
        });

        $('#ended_at').datetimepicker({
            format: 'Y-m-d',
            timepicker: false,
            minDate: dateToDisable,
            onSelectDate: function(selected) { // if ended_at is selected

                var dt = new Date(selected);
                dt.setDate(selected.getDate() - 1);
                $('#started_at').datetimepicker({
                    maxDate: dt
                });
            }
        });

        $('#ended_at').focus( function() { // if started_at is empty

            var dt = $('#started_at').val();
            if (!dt) {
                $(this).datetimepicker({ minDate: dateToDisable });
            } else {
                dt = new Date(dt);
                dt.setDate(dt.getDate() + 1);
                $(this).datetimepicker({ minDate: dt });
            }
        });

    </script>
{% endblock %}

templates/battle/battle_list.html
{% extends "base.html" %}

{% load static %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Battle List{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-sm-offset-5 col-sm-2 text-center">
            <h3 style="margin-top: 5px;">Battle List</h3>
        </div>

        <div class="col-sm-offset-4 col-sm-1 text-right">
            <a class="btn btn-primary" href="{% url 'battle:battle_new' %}"><i class="fa fa-plus"></i> New</a>
        </div>
    </div>

    <br>

    <table class="table table-striped table-bordered">
        <colgroup>
            <col width="80"/>
            <col width=""/>
            <col width="150"/>
            <col width="150"/>
            <col width="100"/>
            <col width="100"/>
            <col width="80"/>
            <col width="80"/>
            <col width="80"/>
            <col width="80"/>
        </colgroup>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Hashtag1</th>
                <th>Hashtag2</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th colspan="2">Status</th>
                <th colspan="2">Action</th>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}

                {% for battle in object_list %}
                    <tr>
                        <td>BID.{{ battle.id }}</td>
                        <td>{{ battle.battle_name }}</td>
                        <td>{{ battle.hashtag1 }}</td>
                        <td>{{ battle.hashtag2 }}</td>
                        <td>{{ battle.started_at }}</td>
                        <td>{{ battle.ended_at }}</td>
                        {% if battle.status == 'Inactive' %}
                        <td>
                            <i style="color: #a94442;">{{ battle.status }}</i>
                        </td>
                        <td>
                            <a style="color: #999999;"><i class="fa fa-eye"></i> Detail</a>
                        </td>
                        {% else %}
                        <td>
                            <i style="color: #0CB10F;">{{ battle.status }}</i>
                        </td>
                        <td>
                            <a href="{% url 'battle:battle_detail' battle.id %}" style="color: #098E0C;"><i class="fa fa-eye"></i> Detail</a>
                        </td>
                        {% endif %}
                        <td>
                            <a href="{% url 'battle:battle_edit' battle.id %}"><i class="fa fa-pencil"></i> Edit</a>
                        </td>
                        <td>
                            <a href="" data-id="{{ battle.id }}" data-toggle="modal" data-target="#delete_battle_modal" style="color: #FF0000;">
                                <i class="fa fa-times"></i> Delete
                            </a>
                        </td>
                    </tr>
                {% endfor %}

            {% else %}
                <tr>
                    <td colspan="10">
                        <h4 class="text-center" style="color: #999999;"><i>There is no battle between hashtags.</i></h4>
                    </td>
                </tr>
            {% endif %}
        </tbody>
    </table>

    <!-- delete-project modal -->
    <div class="modal fade" id="delete_battle_modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content" style="top: 100px;">
                <form class="form-vertical" id="battle_delete_form" method="post">
                    {% csrf_token %}

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Delete Battle</h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            <label>Are you sure to delete it? </label>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Delete</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal" aria-label="Close">Cancel</button>
                    </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /#delete_battle_modal -->

{% endblock %}

{% block extra_script %}
    <script>
        ///////////////////////////////////////////
        // Delete Battle Modal JS
        ///////////////////////////////////////////
        $('#delete_battle_modal').on('submit', '#battle_delete_form', function () {

            $.ajax({
                type: $(this).attr('method'),
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function() { // on success..
                    location.reload();
                },
                error: function(response) { // on error..
                    alert(response);
                }
            });
            return false;

        });

        // battle details url for deleting process
        $('#delete_battle_modal').on('show.bs.modal', function(event) {

            action_url = '/battle/delete/' + $(event.relatedTarget).data('id');
            $("#battle_delete_form").attr("action", action_url);

        });
    </script>
{% endblock %}